{% set name = "compas_cgal" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c9b7c4146897b84be2230823186e993018e1e3e5e9c5b62cc919e450c3422f7f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  host:
    - pip
    - python
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  run:
    - python
    - compas
    - numpy

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
    - petrasvestartas
