{% set name = "compas_cgal" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c9b7c4146897b84be2230823186e993018e1e3e5e9c5b62cc919e450c3422f7f

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - eigen <3.4
  host:
    - pip
    - setuptools >=66
    - python
    - pybind11
    - cgal-cpp >=5.0,<6.0
    - scip =9.0.0     # [win]
    - scip >=9.1      # [not win]
  run:
    - python
    - eigen <3.4
    - cgal-cpp >=5.0,<6.0
    - libboost-devel
    - mpir            # [win]
    - gmp             # [not win]
    - scip =9.0.0     # [win]
    - scip >=9.1      # [not win]
    - mpfr

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
