{% set name = "compas_cgal" %}
{% set version = "0.5.0" %}
{% set hash = "02265088be8f5138ca1b031a03d311e91b8ed114eaf453373057e094fd678d20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 2
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen <3.4
  host:
    - pip
    - python
    - pybind11
    - cgal-cpp >=5.0
  run:
    - python
    - eigen <3.4
    - cgal-cpp >=5.0
    - boost-cpp
    - mpir  # [win]
    - gmp   # [not win]
    - mpfr
    - nptyping
    - typing_extensions

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
