{% set name = "compas_cgal" %}
{% set version = "0.6.0" %}
{% set hash = "fced7cae4e08555e0c3da3b44759ec81157fd084b265052d0756d6b470d22277" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen <3.4
  host:
    - pip
    - python
    - pybind11
    - cgal-cpp >=5.0
    - scip
  run:
    - python
    - eigen <3.4
    - cgal-cpp >=5.0
    - libboost-devel
    - mpir     # [win]
    - gmp      # [not win]
    - scip
    - mpfr
    - nptyping
    - typing_extensions

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
