{% set name = "compas_cgal" %}
{% set version = "0.3.0" %}
{% set hash = "281b353e49afc8b14f5c81609b8f76e937c88b35fa51565598ab1dac683b675d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen <3.4
  host:
    - pip
    - python
    - pybind11
    - cgal-cpp >=5.0
  run:
    - python
    - eigen <3.4
    - cgal-cpp >=5.0
    - boost-cpp
    - mpir  # [win]
    - gmp   # [not win]
    - mpfr
    - nptyping
    - typing_extensions

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - brgcode
    - gonzalocasas
