{% set name = "compas_cgal" %}
{% set version = "0.1.2" %}
{% set hash = "7ce5e0116fc42327ddb5cf15d029779951fe70c8a378cbe6cec413bfad4f76f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen
  host:
    - pip
    - python
    - pybind11
    - cgal-cpp >=5.0
  run:
    - python
    - eigen
    - cgal-cpp >=5.0
    - boost-cpp
    - mpir  # [win]
    - gmp   # [not win]
    - mpfr
    - nptyping
    - typing_extensions

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: 'COMPAS friendly wrappers for CGAL algorithms.'
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - brgcode
    - gonzalocasas
