{% set name = "compas_cgal" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b39038109d514876d2cf783a4215d551622f9af576f55d85a40b621379e7658d

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - eigen <3.4
  host:
    - pip
    - setuptools >=66
    - python
    - pybind11
    - cgal-cpp >=5.0
    - scip
  run:
    - python
    - eigen <3.4
    - cgal-cpp >=5.0
    - libboost-devel
    - mpir     # [win]
    - gmp      # [not win]
    - scip
    - mpfr

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
