{% set name = "compas_cgal" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7f7c2219267257fc15094ecb5b515f1c14973aa8e11be115698f233dce48feb6

build:
  number: 0
  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}  # [win]
    - {{ PYTHON }} -m pip install . -v

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  host:
    - pip
    - python
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  run:
    - python
    - compas
    - numpy

test:
  imports:
    - compas_cgal
  requires:
    - pytest

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
    - petrasvestartas
