{% set name = "compas_cgal" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6b4df50100f47c755a6a9d4878eca9ebb2e730bc0e8888c80fb81ad24b46cf84

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  host:
    - pip
    - python
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  run:
    - python
    - compas
    - numpy

test:
  imports:
    - compas_cgal
  requires:
    - pytest

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: COMPAS friendly wrappers for CGAL algorithms.
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
    - petrasvestartas
